# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecbe58e45a99330b0c2748e65965d553876c46c0e7c4b3d3b92f337703961053d7ddd1568a0241a51b08d83d083e84f06b8a7b499e43819d80ad2c0ae26dc7a6

test:
  secret_key_base: abf9f7e1a5d61699e2f4803eca2c37e8295b0d2c0a5cdfe44f24324e4c4d8df991b5c792eb62c9ba857c55fb4859631e4588abfae173167d494e63c6aefdf07f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
